import type { Metadata } from "next";
import "./globals.css";
import { montserrat, inter } from "@/lib/font";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Calvary Carpentry Malaysia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${montserrat.variable} w-full font-inter`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
